let message = "hello";
console.log(message);


 let glasses1 = document.querySelector(".glasses_1");
    glasses1.addEventListener("mouseover", e => {
        console.log("hovered");
        img.src = "assets/images/model1.jpeg"
        (glasses1).append(img);
    });

let glasses2 = document.querySelector(".glasses_2");
    glasses2.addEventListener("mouseover", e => {
    console.log("hovered");
});

let glasses3 = document.querySelector(".glasses_3");
    glasses3.addEventListener("mouseover", e => {
    console.log("hovered");
});

let glasses4 = document.querySelector(".glasses_4");
    glasses4.addEventListener("mouseover", e => {
    console.log("hovered");
});
